Repository wearesho-team/bobra-cpa, pull requests merged in 2018-12, with the labels that each got.

#20 configuration travis for multiple databases
  .travis.yml
  composer.json
  composer.lock
Labels: enhancement

#24 Implement link profit CPA network
  README.md
  src/LinkProfit/ConfigInterface.php
  src/LinkProfit/EnvironmentConfig.php
  src/LinkProfit/LeadModel.php
  src/LinkProfit/SendService.php
  tests/Unit/LinkProfit/EnvironmentConfigTest.php
  tests/Unit/LinkProfit/LeadModelTest.php
  tests/Unit/LinkProfit/SendServiceTest.php
Labels: enhancement

#23 Requirements
  README.md
Labels: enhancement

#25 Add LinkProfit to lead sources and web controller
  src/Lead/Source.php
  src/Web/Controller.php
Labels: bug

#26 Add linkprofit to conversion service
  src/Conversion/Sync/Service.php
Labels: invalid

#27 Implement sending additional request to linkprofit
  src/LinkProfit/ConfigInterface.php
  src/LinkProfit/SendService.php
  tests/Unit/LinkProfit/SendServiceTest.php
Labels: invalid

#22 Leads parsing
  README.md
  src/AdmitAd/Lead/Parser.php
  src/Bootstrap.php
  src/Cashka/Lead/Parser.php
  src/DoAffiliate/Lead/Parser.php
  src/FinLine/Lead/Parser.php
  src/Lead/Info.php
  src/Lead/Parser.php
  src/Lead/Parser/Chain.php
  src/Lead/Parser/QueryParams.php
  src/Lead/Service.php
  src/LeadGid/Lead/Parser.php
  src/LeadsSu/Lead/Parser.php
  src/Letmeads/Lead/Parser.php
  src/LinkProfit/Lead/Parser.php
  src/LoanGate/Lead/Parser.php
  src/PrimeLead/Lead/Parser.php
  src/SalesDoubler/Lead/Parser.php
  tests/Unit/AdmitAd/LeadParserTest.php
  tests/Unit/Cashka/LeadParserTest.php
  tests/Unit/DoAffiliate/LeadParserTest.php
  tests/Unit/FinLine/LeadParserTest.php
  tests/Unit/Lead/ParserChainTest.php
  tests/Unit/Lead/ServiceTest.php
  tests/Unit/LeadGid/LeadParserTest.php
  tests/Unit/LeadsSu/LeadParserTest.php
  tests/Unit/Letmeads/LeadParserTest.php
  tests/Unit/LinkProfit/LeadParserTest.php
  tests/Unit/LoanGate/LeadParserTest.php
  tests/Unit/Mocks/ParserMock.php
  tests/Unit/PrimeLead/LeadParserTest.php
  tests/Unit/SalesDoubler/LeadParserTest.php
Labels: enhancement
